baseurl = "https://loisvelasco.github.io/"
title = "Loi's Rants（˶′◡‵˶）"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics: G-91HRLLXQM8

[params]
  author = "Louis Velasco"
  info = "Thoughts, stories, and ideas.╰(▔▽▔)╯"
  description = "Louis Velasco's Personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  # gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/loiSvelasco/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-facebook fa-2x"
  weight = 2
  url = "https://www.facebook.com/louis.superficial.velasco.1/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/itsFafaLoi"


  # Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Portfolio"
  weight = 2
  url = "portfolio/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"