
[[main]]
  name = "Home"
  pageRef = "/"
  weight = -10

[[main]]
  name = "Rants"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Site Information"
  pageRef = "attributions"
  weight = 20
